language: python
cache: pip
install: pip install -r requirements.txt
script: python -m elisa_dnt --help
notifications:
  email:
    on_failure: never
    on_pull_requests: never
deploy:
  provider: pypi
  user: Maxen1996
  on:
    tags: true
    branch:
    - master
    - - "/v?(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
  distributions: sdist
  skip_existing: true
  password:
    secure: JiQFO+9NvDpurYaDGsm6IKtpNpvURtAEkCoWkFeNlLGRoZyjN6I4MuGmQfsZ4o/Nn6NqnvXmH5+3/+jBS56UJSPpEa4OsueV+y9a/ULSYWbliGEQjEasIR9XhHcrhIIkSpSq+wlNGdnKYag1DnXeI5ZnjjmJfxUQgXt3QpD4yED0iCaoa96lkKd9Zxm4R6kBkrtmtSHth2WkKk+tAHGH4dTQIVyTN6f+BFb6yvYVdigo0Ih/Q1AMoCIhen2gKU/u1V1eAEiVp74+3Ymcsgkwvj0r3bbGXV5qTt5b5hPpyqkF6AiIV3K5pqtYwMQwVpadajFcLO4ePLFiTAi+TKbe0tldmfVDJpJrtdzX5qzmbaANvCez+S6nwDRALzG91SXDic2q+DuAh3ARwaUbbJihvwp8FIH0m7YZI3+3/kfoV/c6laoviJJ//KWyJNU1wBYoShrz0u2pmEm5IY+2XByWUdCH4cCitQmU16R3wyyeCbgFVFJ/Ac6zmqBkvtayGcLtFD+pw9PdFBOtF8MBcU7hA3p73DLZWNrEm56m2ZCJIfvyzZnpxzwsMldvMNgl0Kae4PVqA8D/5mgGOcIfUmdAVsoO4102Zj6StQAlLBa647kkPf6z0At1H14V8/v4taibjRkm5357L9VtcmsIIxPqluZyK+MFJT1de46Kxyjoes4=
